AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-nextjs-demo

  Sample SAM Template for serverless-nextjs-demo
  
Globals:
  Function:
    Timeout: 10

Resources:
  NextjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      MemorySize: 512
      PackageType: Image
      Architectures:
        - arm64
      Events:
        HttpEvent:
          Type: HttpApi
    Metadata:
      DockerTag: v1
      DockerContext: ./app
      Dockerfile: Dockerfile
      
Outputs:
  NextjsFunctionURL:
    Description: "API Gateway endpoint URL for Next.js"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"